SECRET_KEY = '123456790'

DATABASE_FILE = './shcp.db'
SQLALCHEMY_DATABALE_URI = 'sqlite:///' + DATABASE_FILE
SQLALCHEMY_ECHO = True

SECURITY_URL_PREFIX = "/admin"
SECURITY_PASSWORD_HASH = "pbkdf2_sha512"
SECURITY_PASSWORD_SALT = "ATGUOHAELKiubahiughaerGOJAEGj"

SECURITY_LOGIN_URL = "/login/"
SECURITY_LOGOUT_URL = "/logout/"
SECURITY_REGISTER_URL = "/register/"

SECURITY_POST_LOGIN_VIEW = "/admin/"
SECURITY_POST_LOGOUT_VIEW = "/admin/"
SECURITY_POST_REGISTER_VIEW = "/admin/"

SECURITY_REGISTERABLE = True
SECURITY_SEND_REGISTER_EMAIL = False
SQLALCHEMY_TRACK_MODIFICATIONS = False

BASIC_AUTH_USERNAME = 'guest'
BASIC_AUTH_PASSWORD = 'guest'